#  https://dart-lang.github.io/linter/lints/index.html
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.dto.dart"
    - "lib/generated/**"
    - "lib/src/proto/**"
    - "test/**"
    - "test_driver/**"
    - "packages_fork/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - non_constant_identifier_names
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_statements
    - unawaited_futures
    - avoid_empty_else
    - avoid_print
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_web_libraries_in_flutter
    - comment_references
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_relative_imports
    - prefer_void_to_null
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    - always_put_control_body_on_new_line
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_escaping_inner_quotes
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_renaming_method_parameters
    - avoid_unnecessary_containers
    - avoid_returning_this
    - avoid_returning_null_for_void
    - avoid_returning_null
    - camel_case_extensions
    - flutter_style_todos
    - file_names
    - exhaustive_cases
    - directives_ordering
    - overridden_fields
    - only_throw_errors
    - no_runtimeType_toString
    - library_prefixes
    - prefer_asserts_with_message
    - parameter_assignments
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_initializing_formals
    - prefer_if_elements_to_conditional_expressions
    - prefer_function_declarations_over_variables
    - prefer_final_in_for_each
    - prefer_interpolation_to_compose_strings
    - prefer_int_literals
    - sized_box_for_whitespace
    - provide_deprecation_message
    - prefer_typing_uninitialized_variables
    - prefer_null_aware_operators
    - prefer_mixin
    - prefer_is_not_operator
    - unnecessary_await_in_return
    - type_annotate_public_apis
    - sort_unnamed_constructors_first
    - void_checks
    - use_string_buffers
    - use_setters_to_change_properties
    - use_raw_strings
    - use_named_constants
    - use_is_even_rather_than_modulo
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - unnecessary_raw_strings
    - unnecessary_parenthesis
    - unnecessary_overrides
    - unnecessary_null_aware_assignments
    - always_declare_return_types
