name: armyknife_stdlib
description: Utils for Flutter app development.
version: 0.0.2+3
homepage: https://github.com/vivitainc/flutter_armyknife_stdlib

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  crypto: ^3.0.1
  semaphore: ^0.2.0
  dartx: ^1.0.0
  runtime_assert: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
